#env:
  #variables:
     # key: "There are no variables"
  #parameter-store:
     # key: "There are no variables"

phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    runtime-versions:
       python: 3.7
    #commands:
      # - There are no build commands
  pre_build:
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
  build:
    commands:
      - python App.py sdist bdist_wheel
  post_build:
    commands:
      - printf '[{"name":"julcon","imageUri":"979882373351.dkr.ecr.ap-south-1.amazonaws.com/pyth-repo"}]' > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
#artifacts:
  #files:
    # - We don't currently preserve any artifacts
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - We don't currently cache anything
